# Generated by Django 5.0.2 on 2024-10-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('date_of_joining', models.DateField()),
                ('position', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=15)),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('personal_phone', models.CharField(max_length=20)),
                ('work_phone', models.CharField(max_length=20)),
                ('personal_email', models.EmailField(max_length=254)),
                ('work_email', models.EmailField(max_length=254)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], max_length=15)),
                ('reporting_manager', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('work_schedule', models.CharField(max_length=50)),
                ('job_related_documents', models.FileField(blank=True, null=True, upload_to='job_docs/')),
                ('id_proofs', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('highest_degree', models.CharField(max_length=50)),
                ('institution_name', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=50)),
                ('year_of_graduation', models.IntegerField()),
                ('certifications', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('children_details', models.TextField(blank=True, null=True)),
                ('dependents', models.TextField(blank=True, null=True)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('pan_number', models.CharField(max_length=10)),
                ('salary_account_details', models.TextField()),
                ('previous_company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=50)),
                ('duration_start', models.DateField()),
                ('duration_end', models.DateField()),
                ('responsibilities', models.TextField()),
                ('reason_for_leaving', models.TextField()),
                ('key_skills', models.TextField()),
                ('proficiency_levels', models.TextField()),
            ],
        ),
    ]
