# Generated by Django 5.0.2 on 2024-10-30 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDashboard', '0002_employee_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='key_skills',
            new_name='bank_branch_address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emergency_contact_name',
            new_name='bank_branch_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ifsc_code',
            new_name='bank_ifsc_code',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emergency_contact_relationship',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='job_title',
            new_name='emergency_city',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='emergency_first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emergency_contact_phone',
            new_name='emergency_home_phone',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='spouse_name',
            new_name='emergency_middle_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='personal_phone',
            new_name='emergency_mobile_phone',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='work_phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_birth',
            new_name='previous_exit_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='children_details',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dependents',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='duration_end',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='duration_start',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_proofs',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='proficiency_levels',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary_account_details',
        ),
        migrations.AddField(
            model_name='employee',
            name='aadhar_file_upload',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_docs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='aadhar_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Name as on Aadhar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='aadhar_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='active_visa',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='employee',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name_on_account',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Name as on Bank Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='btech_memo',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/btech_memo/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='btech_tc',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/btech_tc/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_relationship',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_state',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_zip_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_letter',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/experience_letters/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nda_form',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/nda_forms/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/offer_letters/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Name as on PAN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_upload_file',
            field=models.FileField(blank=True, null=True, upload_to='pan_docs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passbook_file_upload',
            field=models.FileField(blank=True, null=True, upload_to='passbook_docs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_file_upload',
            field=models.FileField(blank=True, null=True, upload_to='passport_docs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='payslips',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/payslips/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_member',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Are you a member of PF?'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_withdrawn',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Have you withdrawn from previous PF account?'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='previous_job_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='previous_work_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_1_company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_1_contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_1_designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_1_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_1_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_2_company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_2_contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_2_designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_2_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_2_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='relieving_letter',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/relieving_letters/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='uan_confirmed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='employee',
            name='uan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_file_upload',
            field=models.FileField(blank=True, null=True, upload_to='visa_docs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='zip_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(verbose_name='Current Address'),
        ),
    ]
